# SurveyJS pipeline for load the latest builds to surveyjs/builds repo

pool:
  vmImage: 'Ubuntu-16.04'

steps:

- checkout: self
  persistCredentials: true
  clean: true

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'install Node.js'

- script: |
    npm install
  displayName: 'install the latest packages from NPM'

- bash: |
    SurveyJSVersion=$(npm info survey-creator version) 
    echo "##vso[task.setvariable variable=SurveyJSVersion]$SurveyJSVersion"
  displayName: 'get SurveyJS latest version and put it to variable'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'node_modules/survey-analytics/'
    Contents: |
      survey.analytics.js
      survey.analytics.css
    TargetFolder: '$(SurveyJSVersion)'
    CleanTargetFolder: true
    OverWrite: true
  displayName: 'copy build files - survey-analytics'


- powershell: |
    echo $(git --version)
    git config --global user.email "kurmanov.work@gmail.com"
    git config --global user.name "dmitrykurmanov"
    git checkout master
    git pull origin master
    git add $(SurveyJSVersion)/*
    git commit -m "released $(SurveyJSVersion)"
    git push origin master
  displayName: 'push new build to the surveyjs/builds repo'
